# https://taskfile.dev

version: "3"

includes:
  infra: infra/Taskfile.yaml
  dir: infra

dotenv:
  - .env

tasks:
  default:
    cmds:
      - task infra:plan
    silent: true
 
  clean:
    desc: Clean all terraform artifacts/assets
    silent: true
    cmds:
      - task infra:clean
 
  format:
    desc: Format terraform files
    silent: true
    dir: infra
    cmds:
      - task infra:format
 
  init:
    desc: Init terraform working directory
    silent: true
    cmds:
      - mkdir -p {{.ROOT_DIR}}/.kube
      - task infra:init

  validate:
    silent: true
    deps:
      - format
    desc: Validate the terraform resources
    cmds:
      - task infra:validate

  create_cluster:
    silent: true
    deps:
      - validate
    desc: Create the GKE cluster
    cmds:
      - task infra:create_cluster

  destroy:
    silent: true
    desc: Destroys terraform resources
    cmds:
      - task infra:destroy

  readme:
    desc: Build the README.md
    silent: true
    cmds:
      - terraform-docs infra > {{.ROOT_DIR}}/README.md

  get_kubeconfig:
    silent: true
    desc: Get Kubeconfig of the cluster
    generates:
      - "{{.ROOT_DIR}}/.kube/config"
    aliases:
      - kubeconfig
    cmds:
      - task infra:get_kubeconfig
  
  show_ksa_patch:
    silent: true
    desc: Show the Workload Identity Patch for KSA
    dir: in
    aliases:
       - ksa_patch
    cmds:
      - task infra:show_ksa_patch
